### ISSUE TITLE
VIDE_Data Is missing

### ISSUE THREAD

**Issue by CaiporaGames** [npc-engine/npc-engine#23]
### Subject of the issue
The namespace VIDE_Data is missing and the component VIDE_Assign is missing too

### Your environment
I am using unity 2020.3.30

### Steps to reproduce
I just open in Unity editor

### Expected behaviour
No appear this two errors on the console

### Actual behaviour
To errors appears:
Assets\NPCEngine\Demo\AdvancedDemo\Scripts\VIDEDialogueSystem.cs(11,26): error CS0246: The type or namespace name 'VIDE_Assign' could not be found (are you missing a using directive or an assembly reference?)

and

Assets\NPCEngine\Demo\AdvancedDemo\Scripts\VIDEDialogueSystem.cs(5,7): error CS0246: The type or namespace name 'VIDE_Data' could not be found (are you missing a using directive or an assembly reference?)

**Comment by eublefar** [comment]
Hi

AdvancedDemo scene depends on some free Asset Store packages, you can find references to them on our [asset store page](https://assetstore.unity.com/packages/tools/ai/npc-engine-208498) under Package dependencies tab.

You can either import them to your project or just do not import `NPCEngine\Demo\AdvancedDemo` folder when importing NPCEngine (or just delete it if package already imported). 

I guess I'll just move advanced demo to separate package on the next release, so that it does not cause confusion and throw immediate errors on import :)

**Comment by eublefar** [comment]
Does this fix your issue?
